name: Release

on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta

concurrency:
  group: publish-${{ github.ref }}

env:
  NODE_VERSION: 20

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          # NOTE: ^19 is ESM and was causing a break
          semantic_version: ^18
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
          # Config override used disable features of @semantic-release/github causing rate limit
          # @semantic-release/exec is installed internally
          extends: |
            @side/semantic-config-base
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
